spring.application.name=zona_fit
# Conexion MySql
spring.datasource.url=jdbc:mariadb://localhost:3306/zona_fit_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Enviar que se cree el esquema de bd
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
# Desactivar tomcat
spring.main.web-application-type=none